name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 0 * * *"      # 可修改 "*/10 * * * *" 每10分钟 action，方便调试
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: Mengfanjun020906/waka-box@master  # 原 matchai/waka-box，修改成自己的
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 38913796d6d4f3f471baa354fdaf2aeb
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
